### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by connordoner** [alphagov/notifications-govuk-alerts#87]
Out of curiosity, folk: are you in a position to elaborate on how alert data will be sourced when alerts are sent, e.g. a REST API, somehow being automatically added to data.yaml, etc?

**Comment by quis** [comment]
Hey Connor, thanks for the interest in our project. The people sending the alerts will be using [GOV.UK Notify](https://www.gov.uk/notify) so that’s where the data will come from. We have not decided on the best way for this app to consume that data yet, but the intention is for it to be automated.

**Comment by connordoner** [comment]
Thanks, @quis - interesting to hear. Does GOV.UK Notify now support cell broadcast, or is that being outsourced to MNOs?

**Comment by quis** [comment]
It depends what you mean by ‘supports’. Relevant public authorities will be able to use GOV.UK Notify to write the content of alerts and choose the areas they are broadcast to. Notify then asks MNOs to broadcast the alerts. Hopefully in a few months’ time we’ll be able to [blog](https://gds.blog.gov.uk/) about the infrastructure behind this.

There also some discussion about a standard data format for publishing alerts going on at https://github.com/alphagov/open-standards/issues/73

Going to close this issue for now, hopefully that’s been helpful.

**Comment by connordoner** [comment]
Thanks, Chris — some really fascinating and important work you're doing here! Take care.
